"""initial migration

Revision ID: 0e587d63b77a
Revises: 
Create Date: 2026-01-07 18:28:06.982701

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0e587d63b77a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scripts',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('tags', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'PENDING', 'COMPLETED', 'FAILED', name='scriptstatus'), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scripts_id'), 'scripts', ['id'], unique=False)
    op.create_index(op.f('ix_scripts_name'), 'scripts', ['name'], unique=False)
    op.create_table('generated_scripts',
    sa.Column('script_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('tags', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'PENDING', 'COMPLETED', 'FAILED', name='scriptstatus'), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['script_id'], ['scripts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_generated_scripts_id'), 'generated_scripts', ['id'], unique=False)
    op.create_index(op.f('ix_generated_scripts_name'), 'generated_scripts', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_generated_scripts_name'), table_name='generated_scripts')
    op.drop_index(op.f('ix_generated_scripts_id'), table_name='generated_scripts')
    op.drop_table('generated_scripts')
    op.drop_index(op.f('ix_scripts_name'), table_name='scripts')
    op.drop_index(op.f('ix_scripts_id'), table_name='scripts')
    op.drop_table('scripts')
    # ### end Alembic commands ###
