"""add index to models

Revision ID: 2802853ca6a0
Revises: 5b98980d9c4e
Create Date: 2026-01-08 09:24:55.354809

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2802853ca6a0'
down_revision: Union[str, Sequence[str], None] = '5b98980d9c4e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_generated_scripts_model_name'), 'generated_scripts', ['model_name'], unique=False)
    op.create_index(op.f('ix_generated_scripts_tags'), 'generated_scripts', ['tags'], unique=False)
    op.create_index(op.f('ix_scripts_tags'), 'scripts', ['tags'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_scripts_tags'), table_name='scripts')
    op.drop_index(op.f('ix_generated_scripts_tags'), table_name='generated_scripts')
    op.drop_index(op.f('ix_generated_scripts_model_name'), table_name='generated_scripts')
    # ### end Alembic commands ###
