"""add model_name to generated_scripts

Revision ID: 5b98980d9c4e
Revises: 0e587d63b77a
Create Date: 2026-01-08 04:33:36.577973

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5b98980d9c4e'
down_revision: Union[str, Sequence[str], None] = '0e587d63b77a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('generated_scripts', sa.Column('model_name', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('generated_scripts', 'model_name')
    # ### end Alembic commands ###
